version: '2'
services: 
  golang:
    build: 
      context: .
      dockerfile: ./docker/go/Dockerfile
    container_name: "beego_test"
    ports: 
     - "8080:8080"
    network_mode: "test-net"
    depends_on:
      - mysql
    restart: always
  mysql:
    build: ./docker/mysql
    container_name: "mydb_test"
    network_mode: "test-net"
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #你的root密码
      MYSQL_ROOT_HOST: "%"
    ports: 
     - "3307:3306"